function Conditions(props) {
  return (
      <div style={{maxWidth: "800px", padding: "30px 20px", margin:"auto"}}>
        <h2 style={{textAlign:"center", marginBottom:'4rem'}}>Conditions Générales d’Utilisation de l’Application Mobile RAPIDE REPARATION</h2>
        <div style={{textAlign:"justify"}}>
        <p><span ><strong>ARTICLE 1</strong></span><strong>&nbsp;: INTRODUCTION</strong></p>
        <p><strong>RAPIDE REPARATION SARL (2R), au capital de 1&nbsp;000&nbsp;000 FCFA,</strong> RCCM CI-ABJ-2020-B-12586 Sise la Rivi&eacute;ra golf im BIA apt 501, non loin de la grande mosqu&eacute;e, Repr&eacute;sent&eacute; par AISSO G. Eric Comlan son Directeur G&eacute;n&eacute;ral.</p>
        <p><span>&nbsp;</span>ci-apr&egrave;s d&eacute;nomm&eacute;e &laquo; l&rsquo;Application Mobile &raquo;</p>
        <p>L&rsquo;adresse &eacute;lectronique du contact est : <span >infos@rapide-reparation.ci&nbsp;</span><span>&nbsp;</span></p>
        <p><br /></p>
        <p><span ><strong>ARTICLE 2</strong></span><strong>&nbsp;: OBJET ET CHAMP D&rsquo;APPLICATION DES CGU <span>&nbsp;</span></strong></p>
        <p>Les pr&eacute;sentes Conditions G&eacute;n&eacute;rales d&rsquo;Utilisation d&eacute;crites ci-apr&egrave;s et ci-apr&egrave;s d&eacute;nomm&eacute;es &laquo; CGU &raquo;, r&eacute;gissent les rapports entre RAPIDE REPARATION et les Utilisateurs, ci- apr&egrave;s d&eacute;nomm&eacute;s &laquo; l&rsquo;Utilisateur &raquo; ou &laquo; les Utilisateurs &raquo; de l&rsquo;Application Mobile, et s&rsquo;appliquent sans restriction ni r&eacute;serve pour toute utilisation ou t&eacute;l&eacute;chargement de l&rsquo;Application Mobile. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur est tenu d&rsquo;accepter les pr&eacute;sentes CGU pour tout t&eacute;l&eacute;chargement et pour toute utilisation de l&rsquo;Application Mobile en cochant la case <em>&laquo; Je reconnais avoir lu et</em> <em>accept&eacute; les Conditions G&eacute;n&eacute;rales d&rsquo;Utilisation &raquo;.</em><span ><em><span>&nbsp;</span></em></span></p>
        <p>Les pr&eacute;sentes CGU sont accessibles &agrave; tout moment dans l&rsquo;Application Mobile dans la rubrique &laquo; C.G.U &raquo; qui se trouve dans le MENU PRINCIPAL et pr&eacute;vaudront, le cas &eacute;ch&eacute;ant, sur toute autre version ou tout autre document contradictoire. <span>&nbsp;</span></p>
        <p>RAPIDE REPARATION pourra modifier les pr&eacute;sentes CGU &agrave; tout moment, sans pr&eacute;avis. Les Utilisateurs seront inform&eacute;s de la modification des pr&eacute;sentes par le biais de la publication des CGU actualis&eacute;es sur l&rsquo;application et par une notification signalant ce changement au sein de l&rsquo;application. Les CGU modifi&eacute;es prendront effet &agrave; partir de leur publication. La poursuite de l&rsquo;utilisation du Service suite &agrave; cette publication constituera une acceptation de la nouvelle version des pr&eacute;sentes. <span>&nbsp;</span></p>
        <p>Il est donc conseill&eacute; aux Utilisateurs de lire tr&egrave;s attentivement les pr&eacute;sentes CGU et de consulter r&eacute;guli&egrave;rement les CGU mises &agrave; jour, dans la Rubrique &laquo; C.G.U &raquo; de l&rsquo;Application Mobile ou sur l&rsquo;onglet &laquo; Conditions g&eacute;n&eacute;rales d&rsquo;utilisation &raquo; du site RAPIDE REPARATION (<span >www.rapide-reparation.ci</span>). <span>&nbsp;</span></p>
        <p>Dans le cas o&ugrave; un Utilisateur n&rsquo;accepterait pas les pr&eacute;sentes CGU ou refuserait de s&rsquo;y conformer, il ne doit pas utiliser l&rsquo;Application Mobile. Dans ce cas, il est recommand&eacute; ́ de d&eacute;sinstaller l&rsquo;Application Mobile. En proc&eacute;dant &agrave; son Inscription, l&rsquo;Utilisateur confirme avoir pris connaissance des pr&eacute;sentes CGU et accepte de s&apos;y soumettre sans r&eacute;serve. <span>&nbsp;</span></p>
        <p>Sauf preuve contraire, les donn&eacute;es enregistr&eacute;es dans le syst&egrave;me informatique de l&rsquo;Application Mobile constituent la preuve de l&rsquo;ensemble des transactions conclues avec les Utilisateurs. <span>&nbsp;</span></p>
        <p><span ><strong>ARTICLE 3</strong></span><strong>&nbsp;: PR&Eacute;SENTATION G&Eacute;N&Eacute;RALE DU SERVICE <span>&nbsp;</span></strong></p>
        <p><strong>3.1 Objet du Service <span>&nbsp;</span></strong></p>
        <p>Le Service est une application qui offre l&rsquo;acc&egrave;s &agrave; des solutions en Plomberie, Electricit&eacute;, &eacute;tanch&eacute;it&eacute;, ma&ccedil;onnerie, menuiserie, froid et climatisation, soudure, carrelage, peinture, am&eacute;nagement, d&eacute;m&eacute;nagement, nettoyage, jardinage, d&eacute;sinfection dans les locaux professionnels et particuliers.</p>
        <p>Cette application est n&eacute;e de la volont&eacute; de facilit&eacute; l&rsquo;acc&egrave;s aux services li&eacute;s &agrave; la remise en &eacute;tat de vos bureaux et appartements.<span>&nbsp;</span></p>
        <p><strong>3.2 Fonctionnement du Service <span>&nbsp;</span></strong></p>
        <p>L&rsquo;Application Mobile RAPIDE REPARATION peut &ecirc;tre t&eacute;l&eacute;charg&eacute;e via les boutiques d&rsquo;applications mobiles (telles que notamment Google Play ou l&rsquo;App Store) au moyen des technologies disponibles, et notamment d&apos;un terminal mobile de type smartphone. <span>&nbsp;</span></p>
        <p>Pour b&eacute;n&eacute;ficier du Service, l&rsquo;Utilisateur doit donc disposer d&rsquo;un smartphone, d&rsquo;un acc&egrave;s internet et d&rsquo;un Compte personnel d&rsquo;Utilisateur (cf. Article 4). <span>&nbsp;</span></p>
        <p>Les fonctionnalit&eacute;s de l&rsquo;Application Mobile POPMOMS sont les suivantes : <span>&nbsp;</span></p>
        <ul >
            <li >L&rsquo;Utilisateur renseigne les informations n&eacute;cessaires pour la cr&eacute;ation d&rsquo;un Compte personnel d&rsquo;Utilisateur conform&eacute;ment &agrave; l&rsquo;article 4 ; <span>&nbsp;</span></li>
            <li >L&rsquo;Utilisateur &agrave; la possibilit&eacute; de commander une prestation sp&eacute;cifique sur la plateforme<span>&nbsp;</span></li>
            <li >Si deux Utilisateurs a &eacute;galement la possibilit&eacute; de commander des prestations d&rsquo;urgences.<span>&nbsp;</span></li>
            <li >L&rsquo;Utilisateur peut potentiellement prendre part &agrave; des jeux et b&eacute;n&eacute;ficier de promotions<span>&nbsp;</span></li>
        </ul>
        <p><br /></p>
        <p><span ><strong>ARTICLE 4</strong></span><strong>&nbsp;: CR&Eacute;ATION D&rsquo;UN COMPTE PERSONNEL D&rsquo;UTILISATEUR <span>&nbsp;</span></strong></p>
        <p>Pour acc&eacute;der au Service, tout Utilisateur doit pr&eacute;alablement proc&eacute;der &agrave; son Inscription en cr&eacute;ant un Compte personnel/Entreprise d&rsquo;Utilisateur. <span>&nbsp;</span></p>
        <p>Afin de cr&eacute;er un Compte personnel d&rsquo;Utilisateur, l&rsquo;Utilisateur doit s&apos;inscrire en remplissant le formulaire d&apos;inscription au d&eacute;marrage de l&rsquo;Application Mobile et renseigner les informations suivantes : Pr&eacute;nom, Nom de Famille, Adresse, Email, photo du parent, mot de passe choisi, num&eacute;ro de t&eacute;l&eacute;phone, nombre d&rsquo;enfants, Pr&eacute;nom du ou des enfants, &acirc;ge du ou des enfants, photo des enfants (optionnel), &eacute;cole/cr&egrave;che ou tout autre &eacute;tablissement fr&eacute;quent&eacute; ́ par le ou les enfants de l&rsquo;Utilisateur. <span>&nbsp;</span></p>
        <p >Les informations qui seront visibles sur le profil de l&rsquo;Utilisateur sont les suivantes : <span>&nbsp;</span></p>
        <ul >
            <li >Pr&eacute;nom, (Particulier)</li>
            <li >Premi&egrave;re lettre du Nom Famille, (Particulier)<span>&nbsp;</span></li>
            <li >Raison sociale (Entreprise)</li>
            <li >N&deg; RCCM (Entreprise)</li>
            <li >N&deg; CC (Entreprise)</li>
            <li >E-mail</li>
            <li >Contact</li>
            <li >Adresse<span>&nbsp;</span></li>
        </ul>
        <p ><span>&nbsp;</span></p>
        <p>La validation du Compte personnel/Entreprise d&rsquo;Utilisateur est formalis&eacute;e apr&egrave;s v&eacute;rification du mail, par l&rsquo;envoi d&rsquo;un courriel &agrave; l&rsquo;adresse email renseign&eacute;e par l&rsquo;Utilisateur dans le formulaire d&rsquo;inscription. <span>&nbsp;</span></p>
        <p>En cas d&rsquo;oubli de mot de passe, il suffit de cliquer sur &laquo; mot de passe oubli&eacute; &raquo; et l&rsquo;application envoie &agrave; l&rsquo;adresse e-mail de l&rsquo;utilisateur un lien permettant de le red&eacute;finir. <span>&nbsp;</span></p>
        <p>Le renseignement de ces donn&eacute;es et la validation du compte personnel/Entreprise sont indispensables &agrave; la fourniture du Service. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur s&rsquo;engage &agrave; fournir des informations vraies, sinc&egrave;res, compl&egrave;tes et toujours &agrave; jour. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur reste seul responsable de tout usage qui pourrait &ecirc;tre fait de ses identifiants et mot de passe, et de leur confidentialit&eacute;, ainsi que de toute ́ utilisation de son Compte personnel/Entreprise. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur s&apos;engage &agrave; informer imm&eacute;diatement RAPIDE REPARATION de toute utilisation ou risque d&rsquo;utilisation frauduleuse de son Compte personnel, et de toute atteinte a ̀ la confidentialit&eacute; ́ et a ̀ la s&eacute;curit&eacute; ́ de ses identifiants et mot de passe &agrave; l&rsquo;adresse &eacute;lectronique de contact : <span >infos@rapide-reparation.ci&nbsp;</span><span>&nbsp;</span></p>
        <p>RAPIDE REPARATION ne pourra en aucun cas &ecirc;tre tenue responsable de toute perte ou vol ou tout dommage r&eacute;sultant de la perte ou du vol ou d&rsquo;une utilisation frauduleuse des donn&eacute;es d&rsquo;identifications des Utilisateurs. <span>&nbsp;</span></p>
        <p><br /></p>
        <p><span ><strong>ARTICLE 5</strong></span><strong>&nbsp;: TARIFS ET MODALIT&Eacute;S FINANCIERES <span>&nbsp;</span></strong></p>
        <p>Le t&eacute;l&eacute;chargement et l&rsquo;utilisation de l&rsquo;Application Mobile RAPIDE REPARATION sont gratuits. <span>&nbsp;</span></p>
        <p>L&rsquo;Application Mobile t&eacute;l&eacute;charg&eacute;e gratuitement permet d&rsquo;acc&eacute;der &agrave; tous les services propos&eacute;s tels que d&eacute;crits &agrave; l&rsquo;Article 3 des pr&eacute;sentes. <span>&nbsp;</span></p>
        <p><span ><strong>ARTICLE 6</strong></span><strong>&nbsp;: OBLIGATIONS DE L&rsquo;UTILISATEUR <span>&nbsp;</span></strong></p>
        <p>Le Service RAPIDE REPARATION a pour finalit&eacute; de favoriser l&rsquo;entraide r&eacute;ciproque entre Utilisateurs, et de leur donner acc&egrave;s &agrave; des services divers et &agrave; des &laquo; bons plans &raquo;. Toute utilisation du Service contraire &agrave; cette finalit&eacute; sera contraire aux pr&eacute;sentes CGU. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur reconnait disposer de la comp&eacute;tence et des moyens techniques n&eacute;cessaires pour t&eacute;l&eacute;charger et utiliser l&rsquo;Application Mobile, le mat&eacute;riel utilis&eacute; restant exclusivement &agrave; sa charge. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur est notamment inform&eacute; du fait que l&rsquo;utilisation du Service peut n&eacute;cessiter l&rsquo;acceptation de la g&eacute;olocalisation lorsqu&rsquo;il utilise l&rsquo;Application Mobile pour une bonne utilisation du Service. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur s&rsquo;engage &agrave; faire une utilisation ad&eacute;quate et licite du Service et de ses contenus, conform&eacute;ment &agrave; la l&eacute;gislation en vigueur, les pr&eacute;sentes CGU, la morale, les bonnes m&oelig;urs et l&rsquo;ordre public.<span>&nbsp;&nbsp;</span><span ><em><span>&nbsp;</span></em></span></p>
        <p>Les Utilisateurs qui utilisent le Service pour des finalit&eacute;s interdites par la Loi et/ou contraires aux pr&eacute;sentes seront expos&eacute;s &agrave; des poursuites judiciaires et les donn&eacute;es permettant leur identification pourront &ecirc;tre fournies aux autorit&eacute;s comp&eacute;tentes en cas de proc&eacute;dure judiciaire engag&eacute;e contre eux. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur est inform&eacute; qu&rsquo;il lui est formellement interdit : <span>&nbsp;</span></p>
        <ul >
            <li >D&rsquo;entreprendre une utilisation non-autoris&eacute;e ou frauduleuse de l&rsquo;Application Mobile et/ou de ses contenus &agrave; des fins ou effets illicites ; <span>&nbsp;</span></li>
            <li >D&rsquo;acc&eacute;der ou essayer d&rsquo;acc&eacute;der &agrave; des ressources ou aires restreintes de l&rsquo;Application Mobile, sans respecter les conditions exig&eacute;es pour cet acc&egrave;s ; <span>&nbsp;</span></li>
            <li >D&rsquo;introduire ou de diffuser sur le r&eacute;seau des virus informatiques ou tout autre syst&egrave;me physique ou logique qui soient susceptibles de provoquer des dommages sur les syst&egrave;mes physiques ou logiques du propri&eacute;taire de l&rsquo;Application Mobile, de ses fournisseurs, des autres Utilisateurs ou de tout tiers ; <span>&nbsp;</span></li>
            <li >De diffuser toute donn&eacute;e, information ou contenu ayant un caract&egrave;re diffamatoire, injurieux, obsc&egrave;ne, raciste ou x&eacute;nophobe, choquant, incitant &agrave; la haine ou la violence, mena&ccedil;ante, constitutive de harc&egrave;lement, et de mani&egrave;re g&eacute;n&eacute;rale tout contenu qui serait contraire aux lois et r&egrave;glements en vigueur, aux bonnes m&oelig;urs, ou &agrave; l&rsquo;ordre public. <span>&nbsp;</span></li>
            <li >De t&eacute;l&eacute;charger, envoyer, diffuser transmettre tout Contenu qui pourrait &ecirc;tre constitutif de fausse d&eacute;claration, d&apos;atteinte a ̀ l&apos;autorit&eacute; ́ de la Justice ou qui contiendrait des informations confidentielles ; <span>&nbsp;</span></li>
        </ul>
        <p><br /></p>
        <p >Conform&eacute;ment &agrave; l&apos;article 6. I. alin&eacute;a 7 de la Loi n&deg; 2004-575 du 21 juin 2004 pour la confiance dans l&apos;&eacute;conomie num&eacute;rique, l&rsquo;Application Mobile permet aux Utilisateurs du Service, par l&rsquo;interm&eacute;diaire du Formulaire de Contact, ou directement via l&rsquo;Application Mobile de porter &agrave; la connaissance de RAPIDE REPARATION tout comportement qui lui semble illicite et/ou contraire aux pr&eacute;sentes CGU<span >.</span></p>
        <p ><br /></p>
        <p><span ><strong>ARTICLE 7</strong></span><strong>&nbsp;: OBLIGATIONS DE RAPIDE REPARATION<span>&nbsp;</span></strong></p>
        <p>RAPIDE REPARATION s&apos;engage &agrave; fournir un Service conforme aux pr&eacute;sentes CGU. <span>&nbsp;</span></p>
        <p>RAPIDE REPARATION se r&eacute;serve le droit de modifier toute information ou contenu figurant dans l&rsquo;Application Mobile, &agrave; tout moment et sans pr&eacute;avis, dans le cadre de sa mise &agrave; jour ou de la correction d&apos;erreurs ou d&apos;inexactitudes ou si cela lui semble opportun sans que cela ouvre droit &agrave; une quelconque r&eacute;paration pour les Utilisateurs. <span>&nbsp;</span></p>
        <p>En cas de violation des pr&eacute;sentes CGU ou des lois et r&egrave;glements en vigueur, notamment en cas de manquement par un Utilisateur &agrave; l&apos;une ou plusieurs des r&egrave;gles pr&eacute;cit&eacute;es &agrave; l&rsquo;Article 6, ou dont le comportement pourrait compromettre ou risquer de compromettre le bon fonctionnement du Service ou porter atteinte aux droits des tiers ou &agrave; la r&eacute;putation du Service, RAPIDE REPARATION se r&eacute;serve le droit de suspendre et/ou de r&eacute;silier unilat&eacute;ralement l&rsquo;ex&eacute;cution des pr&eacute;sentes dans les conditions vis&eacute;es &agrave; l&rsquo;Article 10 des pr&eacute;sentes, et de bloquer et/ou supprimer le Compte personnel/Entreprise de l&rsquo;Utilisateur concern&eacute; ainsi que son acc&egrave;s &agrave; tout ou partie du Service, de fa&ccedil;on temporaire ou d&eacute;finitive, sans que cela ouvre droit pour l&rsquo;Utilisateur a ̀ une quelconque indemnit&eacute;. ́<span>&nbsp;</span></p>
        <p><br /></p>
        <p><span ><strong>ARTICLE 8</strong></span><strong>&nbsp;: LIMITATION DE RESPONSABILIT&Eacute;S <span>&nbsp;</span></strong></p>
        <p>&Agrave; tout moment, RAPIDE REPARATION pourra modifier, interrompre temporairement ou d&eacute;finitivement l&rsquo;acc&egrave;s au Service, et ce, sans avoir &agrave; en informer les internautes au pr&eacute;alable, RAPIDE REPARATION ne prenant aucun engagement de maintenir un acc&egrave;s permanent et interrompu &agrave; l&rsquo;Application Mobile et/ou au Service. RAPIDE REPARATION n&rsquo;est en aucun cas responsable de ces interruptions et des cons&eacute;quences qui peuvent en d&eacute;couler pour l&rsquo;Utilisateur. <span>&nbsp;</span></p>
        <p>RAPIDE REPARATION ne sera pas responsable du fonctionnement inad&eacute;quat du Service s&rsquo;il r&eacute;sulte d&rsquo;op&eacute;rations de maintenance, d&rsquo;incidents, ou de probl&egrave;mes li&eacute;s &agrave; sa capacit&eacute; &agrave; supporter les syst&egrave;mes indispensables &agrave; l&rsquo;utilisation du service, m&ecirc;me si RAPIDE REPARATION fera ses meilleurs efforts pour assurer une r&eacute;ponse rapide, sans se responsabiliser pour les retards li&eacute;s aux services de t&eacute;l&eacute;communications. Notamment, RAPIDE REPARATION ne sera en aucun cas responsable du mauvais fonctionnement des op&eacute;rateurs t&eacute;l&eacute;phoniques et des fournisseurs d&rsquo;acc&egrave;s Internet auxquels l&rsquo;Utilisateur aura eu recours, ni des plateformes de moyens de paiement que l&rsquo;Utilisateur emploierait pour effectuer les paiements.<span>&nbsp; &nbsp; &nbsp;</span></p>
        <p>L&rsquo;Utilisateur reste seul responsable de tout usage qui pourrait &ecirc;tre fait de ses identifiants et mot de passe, et de leur confidentialit&eacute;, ainsi que de toute utilisation de son ́ Compte personnel. RAPIDE REPARATION ne pourra en aucun cas &ecirc;tre tenue responsable de toute perte ou vol ou tout dommage r&eacute;sultant d&rsquo;une utilisation frauduleuse des donn&eacute;es d&rsquo;identification des Utilisateurs.<span>&nbsp; &nbsp;</span></p>
        <p>En tant que prestataire technique, RAPIDE REPARATION n&rsquo;est pas tenue de v&eacute;rifier la v&eacute;racit&eacute; des informations fournies par les Utilisateurs et d&eacute;cline toute responsabilit&eacute; ́ quant &agrave; l&apos;inexactitude des donn&eacute;es, informations et contenus diffus&eacute;s par les Utilisateurs via l&rsquo;Application Mobile, ou des erreurs ou omissions qu&rsquo;ils pourraient comporter ainsi que tout dommage cons&eacute;cutif &agrave; l&apos;utilisation de tout contenu fournit par un Utilisateur. <span>&nbsp;</span></p>
        <p><span>&nbsp;</span>RAPIDE REPARATION n&rsquo;offre aucune garantie quant au fonctionnement et &agrave; la disponibilit&eacute; ́ dans l&rsquo;acc&egrave;s &agrave; l&rsquo;Application Mobile RAPIDE REPARATION en cas de survenance de cas de force majeure ou de cas fortuit tels que d&eacute;finis par la r&egrave;glementation et la jurisprudence en vigueur. <span>&nbsp;</span></p>
        <p>De fa&ccedil;on expresse, sont consid&eacute;r&eacute;es, notamment, mais pas exclusivement, comme cas de force majeure ou cas fortuits, outre ceux habituellement retenus par la jurisprudence des juridictions Ivoirienne : les intemp&eacute;ries exceptionnelles les gr&egrave;ves totales ou partielles, internes ou externes &agrave; l&rsquo;entreprise, &eacute;pid&eacute;mies, blocage des moyens de transports ou d&rsquo;approvisionnement pour quelque raison que ce soit, tremblement de terre, incendies, temp&ecirc;tes, inondations, d&eacute;g&acirc;ts des eaux, les catastrophes naturelles, la foudre, les attentats, les dommages provoqu&eacute;s par des virus pour lesquels les moyens de s&eacute;curit&eacute; ́ existant sur le march&eacute; ne permettent pas leur &eacute;radication, ainsi que toute obligation l&eacute;gale ou r&egrave;glementaire ou d&apos;ordre public impos&eacute;e par les autorit&eacute;s comp&eacute;tentes et qui auraient pour effet de modifier substantiellement les pr&eacute;sentes conditions g&eacute;n&eacute;rales, les pannes d&rsquo;ordinateur, le blocage des t&eacute;l&eacute;communications y compris le r&eacute;seau P.T.T., la d&eacute;faillance du r&eacute;seau public des t&eacute;l&eacute;communications, les pertes de connectivit&eacute; Internet dues aux op&eacute;rateurs publics ou priv&eacute;s, tout probl&egrave;me li&eacute; au modem ou au syst&egrave;me informatique de l&rsquo;Utilisateur ou son logiciel de navigation, les interconnexions de r&eacute;seaux t&eacute;l&eacute;phoniques et/ou toute autre infrastructure de t&eacute;l&eacute;communications employ&eacute;e par l&rsquo;utilisateur, la d&eacute;faillance du r&eacute;seau public de distribution d&rsquo;&eacute;lectricit&eacute; ́ et tout autre &eacute;v&egrave;nement ind&eacute;pendant de la volont&eacute; ́ expresse des parties emp&ecirc;chant l&rsquo;ex&eacute;cution normale du Service. <span>&nbsp;</span></p>
        <p>RAPIDE REPARATION n&rsquo;est pas non plus responsable de la mauvaise configuration du terminal mobile de l&rsquo;Utilisateur. Il appartient &agrave; chaque Utilisateur de s&rsquo;assurer du bon fonctionnement et de la configuration de son mat&eacute;riel.<span>&nbsp; &nbsp;</span></p>
        <p><span ><strong>ARTICLE 9</strong></span><strong>&nbsp;: DUREE</strong> <span>&nbsp;</span></p>
        <p>Dans le cas du t&eacute;l&eacute;chargement de l&rsquo;Application Mobile gratuite, les pr&eacute;sentes CGU sont souscrites pour une dur&eacute;e ind&eacute;termin&eacute;e &agrave; compter de leur acceptation par l&rsquo;Utilisateur dans les conditions d&eacute;crites &agrave; l&rsquo;Article 1. <span>&nbsp;</span></p>
        <p><span ><strong>ARTICLE 10</strong></span><strong>&nbsp;: RESILIATION <span>&nbsp;</span></strong></p>
        <p>L&apos;acc&egrave;s &agrave; l&rsquo;Application Mobile et au Service pourrait &ecirc;tre interrompu temporairement ou d&eacute;finitivement, notamment en cas de cessation par RAPIDE REPARATION de l&apos;activit&eacute; en cause, ou en cas de liquidation judiciaire ou amiable de la soci&eacute;t&eacute; ́ RAPIDE REPARATION. Les pr&eacute;sentes CGU seraient alors r&eacute;sili&eacute;es de plein droit. <span>&nbsp;</span></p>
        <p>En cas de d&eacute;c&egrave;s de l&rsquo;Utilisateur, les relations contractuelles entre celui-ci et RAPIDE REPARATION seront r&eacute;sili&eacute;es de plein droit et son Compte personnel sera d&eacute;sactiv&eacute;, sur production ́ des pi&egrave;ces justificatives pertinentes des ayants droit. Son contenu ne pourra &ecirc;tre transmis aux ayants droit que sur d&eacute;cision de Justice.<span>&nbsp; &nbsp;</span></p>
        <p>En cas de violation des pr&eacute;sentes par l&rsquo;Utilisateur, ou des lois et r&egrave;glements en vigueur, notamment, mais pas exclusivement, en cas de manquement par un Utilisateur &agrave; l&apos;une ou plusieurs des r&egrave;gles pr&eacute;cit&eacute;es &agrave; l&rsquo;Article 6, ou en cas de comportement compromettant ou risquant de compromettre le bon fonctionnement du Service ou porter atteinte aux droits des tiers ou &agrave; la r&eacute;putation du Service, RAPIDE REPARATION se r&eacute;serve le droit de suspendre et/ou de r&eacute;silier unilat&eacute;ralement l&rsquo;ex&eacute;cution des pr&eacute;sentes, et de bloquer et/ou supprimer le Compte personnel de l&rsquo;Utilisateur concern&eacute;, ainsi que son acc&egrave;s &agrave; tout ou partie du Service.</p>
        <p>Tout Utilisateur peut se d&eacute;sinscrire &agrave; tout moment de l&rsquo;Application Mobile en envoyant un mail &agrave; RAPIDE REPARATION sur l&rsquo;adresse suivante&nbsp;: infos@rapide-reparation.com avec pour objet &laquo;&nbsp;D&eacute;sactivation de compte&nbsp;&raquo;</p>
        <p><span ><strong>ARTICLE 11</strong></span><strong>&nbsp;: PROPRI&Eacute;T&Eacute; INTELLECTUELLE ET INDUSTRIELLE <span>&nbsp;</span></strong></p>
        <ul >
            <ul >
                <li ><strong>Titres de propri&eacute;t&eacute; intellectuelle de RAPIDE REPARATION <span>&nbsp;</span></strong></li>
            </ul>
        </ul>
        <p>L&rsquo;ensemble du contenu de l&rsquo;Application Mobile et des Sites Web, les photographies, logos, images, sons, vid&eacute;o, graphiques, textes, ou illustrations ainsi que sa structure, les bases de donn&eacute;es, logiciels, codes ainsi que tout autre mat&eacute;riel et &eacute;l&eacute;ment visuel composant l&rsquo;Application Mobile est prot&eacute;g&eacute;, notamment par le droit de la propri&eacute;t&eacute; ́ intellectuelle dont RAPIDE REPARATION reste le seul titulaire. <span>&nbsp;</span></p>
        <p >Les pr&eacute;sentes CGU n&rsquo;emportent aucune cession d&rsquo;aucune sorte de droits de propri&eacute;t&eacute; ́ intellectuelle sur les &eacute;l&eacute;ments appartenant &agrave; RAPIDE REPARATION et/ou &agrave; ses partenaires au b&eacute;n&eacute;fice de l&rsquo;Utilisateur. <span>&nbsp;</span></p>
        <p>Les Utilisateurs s&rsquo;engagent &agrave; respecter les droits de propri&eacute;t&eacute; ́ intellectuelle attach&eacute;s aux &eacute;l&eacute;ments composants l&rsquo;Application Mobile et s&rsquo;interdisent, notamment de les diffuser, publier, transmettre, c&eacute;der &agrave; tout tiers, de les exploiter &agrave; des fins commerciales, de les reproduire, les copier ou les modifier sans autorisation expresse de RAPIDE REPARATION. Notamment, toute extraction ou r&eacute;utilisation des donn&eacute;es contenues dans l&rsquo;Application Mobile, au-del&agrave; de son usage normal est strictement interdite &agrave; tout Utilisateur et est soumise &agrave; l&apos;autorisation expresse et pr&eacute;alable de RAPIDE REPARATION. <span>&nbsp;</span></p>
        <ul >
            <ul >
                <li ><strong>Droit d&rsquo;usage de l&rsquo;Application Mobile par l&rsquo;Utilisateur <span>&nbsp;</span></strong></li>
            </ul>
        </ul>
        <p>L&rsquo;Utilisateur ne dispose que d&apos;un droit d&apos;usage strictement personnel, non exclusif et non transf&eacute;rable de l&rsquo;Application Mobile. Tout autre usage est soumis &agrave; l&rsquo;autorisation pr&eacute;alable et expresse de RAPIDE REPARATION. <span>&nbsp;</span></p>
        <p>Toute reproduction, repr&eacute;sentation ou diffusion, y compris l&rsquo;addition &agrave; celle-ci de nouvelles fonctions ou la r&eacute;alisation de modifications sur celle-ci qui alt&eacute;reraient son fonctionnement, par quelque moyen que ce soit et sur quelque support que ce soit, est formellement interdite, &agrave; la seule exception du droit de reproduire pour stockage aux fins de repr&eacute;sentation pour copie de sauvegarde ou impression sur support papier en un exemplaire, sous condition du respect de l&apos;int&eacute;grit&eacute; ́ des documents. <span>&nbsp;</span></p>
        <p>Le droit d&rsquo;utilisation de l&rsquo;Application Mobile accord&eacute;e en vertu des pr&eacute;sentes CGU pourra &ecirc;tre r&eacute;sili&eacute; &agrave; tout moment par l&rsquo;Utilisateur par la d&eacute;sinstallation de l&rsquo;Application et l&rsquo;&eacute;limination de l&rsquo;ensemble des copies de l&rsquo;Application Mobile sur ses appareils ou par la r&eacute;siliation des pr&eacute;sentes selon les termes de l&rsquo;article 11. <span>&nbsp;</span></p>
        <p><span ><strong>ARTICLE 12</strong></span><strong>&nbsp;: POLITIQUE DE CONFIDENTIALIT&Eacute; ET DONN&Eacute;ES PERSONNELLES <span>&nbsp;</span></strong></p>
        <p><strong>12.1 G&eacute;n&eacute;ralit&eacute;s<span>&nbsp;</span></strong></p>
        <p>Dans le cadre de l&rsquo;ex&eacute;cution de ses prestations, RAPIDE REPARATION est susceptible de collecter des donn&eacute;es personnelles relatives notamment &agrave; la population de personnes physiques objet des prestations command&eacute;es par les Utilisateurs.<span>&nbsp;</span></p>
        <p>La collecte des donn&eacute;es personnelles recueillies par le biais du Service RAPIDE REPARATION est n&eacute;cessaire au bon fonctionnement du Service et est obligatoire pour acc&eacute;der aux services propos&eacute;s via l&rsquo;Application Mobile. <span>&nbsp;</span></p>
        <p>Le d&eacute;faut de communication des donn&eacute;es personnelles obligatoires emp&ecirc;che l&rsquo;acc&egrave;s au Service propos&eacute; par RAPIDE REPARATION. <span>&nbsp;</span></p>
        <p>RAPIDE REPARATION r&eacute;alise la conservation des Donn&eacute;es Personnelles de fa&ccedil;on &agrave; permettre le respect de leur int&eacute;grit&eacute; durant le temps n&eacute;cessaire &agrave; la r&eacute;alisation et la fourniture du Service propos&eacute; et conform&eacute;ment aux dur&eacute;es de conservation impos&eacute;es par la l&eacute;gislation en vigueur. <span>&nbsp;</span></p>
        <p><br /></p>
        <p><strong>12.2 Obligations de RAPIDE REPARATION<span>&nbsp;</span></strong></p>
        <p>RAPIDE REPARATION s&rsquo;engage &agrave; traiter lesdites donn&eacute;es personnelles dans le respect de cette r&egrave;glementation, et &agrave; cet &eacute;gard, s&rsquo;engage &agrave; :<span>&nbsp;</span></p>
        <ul >
            <li >Ne collecter et traiter les donn&eacute;es personnelles que conform&eacute;ment aux instructions expresses de l&rsquo;Utilisateur et aux finalit&eacute;s li&eacute;es &agrave; l&rsquo;objet des services propos&eacute;s via l&rsquo;Application Mobile.<span>&nbsp;</span></li>
            <li >Pr&eacute;server la s&eacute;curit&eacute;, l&rsquo;int&eacute;grit&eacute; et la confidentialit&eacute; des donn&eacute;es personnelles d&egrave;s lors qu&rsquo;il proc&egrave;de &agrave; leur collecte ou leur enregistrement dans le cadre de l&rsquo;ex&eacute;cution des Services<span>&nbsp;</span></li>
            <li >Ne communiquer les donn&eacute;es personnelles &agrave; aucun tiers quel qu&rsquo;il soit, hormis les tiers auxquels il est strictement n&eacute;cessaire de transmettre les donn&eacute;es personnelles en ex&eacute;cution des prestations propos&eacute;es ; Les donn&eacute;es personnelles ainsi collect&eacute;es pourront ainsi &ecirc;tre transmises au Personnel de RAPIDE REPARATION ainsi qu&rsquo;&agrave; tout tiers charg&eacute; de participer &agrave; la mise en place, &agrave; la r&eacute;alisation ou au suivi du Service (personnel, partenaires et/ou sous-traitants). Les membres du Personnel de RAPIDE REPARATION ainsi que les tiers d&eacute;sign&eacute;s par ce dernier, auront acc&egrave;s et pourront utiliser les donn&eacute;es personnelles collect&eacute;es dans le seul but de fournir le Service propos&eacute;. <span>&nbsp;</span></li>
        </ul>
        <p>En aucun cas, les donn&eacute;es personnelles ne seront c&eacute;d&eacute;es &agrave; d&rsquo;autres tiers, que ce soit &agrave; titre gracieux ou on&eacute;reux, sans l&rsquo;autorisation de l&rsquo;Utilisateur, &agrave; l&rsquo;exception des cas pr&eacute;vus &agrave; l&rsquo;article 10 des pr&eacute;sentes qui pr&eacute;voit que les donn&eacute;es permettant l&rsquo;identification de l&rsquo;Utilisateur pourront &ecirc;tre transmises aux ayants droit sur d&eacute;cision de Justice. <span>&nbsp;</span></p>
        <ul >
            <li >Mettre en place tout syst&egrave;me de s&eacute;curisation des donn&eacute;es qui serait requis soit en raison d&rsquo;une analyse d&rsquo;impact men&eacute;e par l&rsquo;Utilisateur en tant que responsable du traitement soit en raison d&rsquo;une l&eacute;gislation sp&eacute;cifique imposant de recourir &agrave; des modalit&eacute;s d&eacute;termin&eacute;es de conservation des donn&eacute;es ;<span>&nbsp;</span></li>
            <li >Alerter sans d&eacute;lai l&rsquo;Utilisateur en cas de violation, de perte ou de divulgation non autoris&eacute;e de donn&eacute;es personnelles collect&eacute;es dans le cadre de l&rsquo;utilisation des Services, afin de permettre &agrave; l&rsquo;Utilisateur d&rsquo;alerter les personnes concern&eacute;es et de se conformer &agrave; ses obligations au sens de la r&egrave;glementation susmentionn&eacute;e.<span>&nbsp;</span></li>
        </ul>
        <p>RAPIDE REPARATION<span>&nbsp;&nbsp;</span>s&rsquo;abstient en toute hypoth&egrave;se de reproduire, exploiter ou utiliser les donn&eacute;es personnelles collect&eacute;es &agrave; l&rsquo;occasion de ses prestations ses propres fins ou pour le compte de tiers, et s&rsquo;engage &agrave; modifier ou supprimer, soit &agrave; la demande de l&rsquo;Utilisateur, soit &agrave; la demande d&rsquo;une personne concern&eacute;e, et en toute hypoth&egrave;se &agrave; l&rsquo;ach&egrave;vement de la finalit&eacute; poursuivie et au terme de l&rsquo;ex&eacute;cution de ses prestations, toute donn&eacute;e personnelle collect&eacute;e &agrave; l&rsquo;occasion ou aux fins d&rsquo;ex&eacute;cution desdites prestations.<span>&nbsp;</span></p>
        <p>Tout Utilisateur peut envoyer une plainte au sujet du respect de la vie priv&eacute;e ou toute question au sujet des informations recueillies et trait&eacute;es par RAPIDE REPARATION &agrave; l&rsquo;adresse &eacute;lectronique suivante : infos@rapide-reparation.ci<span>&nbsp;</span></p>
        <ul >
            <ul >
                <li ><strong>Droit d&rsquo;acc&egrave;s, de rectification et de suppression des donn&eacute;es personnelles<span>&nbsp;</span></strong></li>
            </ul>
        </ul>
        <p>Tout Utilisateur a le droit d&rsquo;acc&eacute;der, de rectifier ou de s&rsquo;opposer au traitement de toute donn&eacute;e le concernant qui ne soit pas indispensable &agrave; la finalit&eacute; du recueil. <span>&nbsp;</span></p>
        <p>A cet effet, au sein des registres informatiques de RAPIDE REPARATION peuvent &ecirc;tre conserv&eacute;s les noms ou pr&eacute;nom, l&rsquo;adresse email, le mot de passe, l&rsquo;adresse IP de l&rsquo;Utilisateur, la marque et le mod&egrave;le de l&rsquo;appareil, l&rsquo;op&eacute;rateur mobile, la date et l&rsquo;heure exacte de publication des informations et contenus transmises via l&rsquo;Application Mobile. <span>&nbsp;</span></p>
        <p><strong>12.4 Utilisation des cookies, identifiants et du fichier d&rsquo;activit&eacute;<span>&nbsp;</span></strong></p>
        <p>Afin d&rsquo;am&eacute;liorer le Service RAPIDE REPARATION en termes de rendement du syst&egrave;me et de facilit&eacute; d&rsquo;usage, ainsi que pour proposer de l&rsquo;information utile sur les produits et services, peuvent &ecirc;tre recueillies automatiquement et conserv&eacute;es des informations dans les fichiers de registre (log files) en provenance des ordinateurs ou terminaux utilis&eacute;s. <span>&nbsp;</span></p>
        <p>Ceci inclut des donn&eacute;es non personnelles telles que l&rsquo;adresse IP, le type de navigateur, langue s&eacute;lectionn&eacute;e, le syst&egrave;me d&rsquo;exploitation, le fournisseur d&rsquo;acc&egrave;s Internet (ISP) ainsi que la date et l&rsquo;heure. Ces informations sont utilis&eacute;es de fa&ccedil;on globale pour am&eacute;liorer la gestion de l&rsquo;Application Mobile, analyser les tendances et recueillir des donn&eacute;es d&eacute;mographiques sur les Utilisateurs. <span>&nbsp;</span></p>
        <p>Si des informations non personnelles sont utilis&eacute;es en combinaison avec les Donn&eacute;es Personnelles, l&rsquo;ensemble sera trait&eacute; en tant que Donn&eacute;es Personnelles et sera d&egrave;s lors trait&eacute; conform&eacute;ment au pr&eacute;sent article 12. <span>&nbsp;</span></p>
        <p>De m&ecirc;me, dans le but d&rsquo;optimiser les services de RAPIDE REPARATION, les messages envoy&eacute;s par courrier &eacute;lectronique, les services onlines, les publicit&eacute;s et les applications interactives peuvent utiliser les &ldquo;cookies&rdquo; ou les &ldquo;identifiants anonymes&rdquo; des utilisateurs (en ce qui concerne les Sites web). <span>&nbsp;</span></p>
        <p>Que sont les cookies ? <span>&nbsp;</span></p>
        <p>Un cookie est un petit fichier, habituellement form&eacute; par des lettres et des nombres, envoy&eacute;s par notre serveur web ou par l&rsquo;Application Mobile &agrave; un fichier de cookies du navigateur de l&rsquo;Utilisateur. Ceci permet &agrave; RAPIDE REPARATION de se souvenir de la pr&eacute;sence d&rsquo;un Utilisateur lors de l&rsquo;&eacute;tablissement d&rsquo;une nouvelle connexion entre au serveur de RAPIDE REPARATION et le navigateur de l&rsquo;Utilisateur. Le principal objectif d&rsquo;un cookie est de permettre au serveur de RAPIDE REPARATION de pr&eacute;senter des pages web personnalis&eacute;es qui puissent faire de la consultation du Service une exp&eacute;rience individuelle et ajust&eacute;e aux pr&eacute;f&eacute;rences personnelles. <span>&nbsp;</span></p>
        <p><strong>12.6 Obligations de l&rsquo;Utilisateur<span>&nbsp;</span></strong></p>
        <p>Il est rappel&eacute; qu&rsquo;il appartient &agrave; l&rsquo;Utilisateur, de s&eacute;lectionner les services souhait&eacute;s et passer la commande. Il peut annul&eacute;e une commande, faire des rectifications ses commandes par envoi d&rsquo;un courriel &agrave; l&rsquo;adresse &eacute;lectronique suivante : <span >infos@rapide-reparation.ci</span><span ><span>&nbsp;&nbsp;</span></span><span >ou<span>&nbsp;</span></span> par appel t&eacute;l&eacute;phonique au +225 25 22 01 61 26</p>
        <p><span>&nbsp;&nbsp;</span></p>
        <p><span ><strong>ARTICLE 13</strong></span><strong>&nbsp;: L&Eacute;GISLATION APPLICABLE &ndash; LITIGES - LANGUE <span>&nbsp;</span></strong></p>
        <p>La conclusion, l&apos;interpr&eacute;tation et la validit&eacute; ́ des pr&eacute;sentes CGU et l&rsquo;ensemble des contrats qui en d&eacute;coulent et leurs suites sont soumis &agrave; la Loi et la R&egrave;glementation fran&ccedil;aise en vigueur, &agrave; l&apos;exclusion de toute autre l&eacute;gislation, quelle que soit la nationalit&eacute; ́ de l&rsquo;Utilisateur, il en est ainsi pour les r&egrave;gles de fond et de formes. <span>&nbsp;</span></p>
        <p>&Agrave; d&eacute;faut d&rsquo;accord amiable entre les parties et en cas d&apos;&eacute;chec des pourparlers, les parties reprendront leur enti&egrave;re libert&eacute; ́ et leur litige sera port&eacute; devant le Tribunal comp&eacute;tent.</p>
        <p>En cas de difficult&eacute; d&apos;interpr&eacute;tation, la version en langue fran&ccedil;aise des pr&eacute;sentes CGU pr&eacute;vaut sur toute autre version qui serait traduite dans une autre langue. <span>&nbsp;</span></p>
        <p><br /></p>
        <p><span ><strong>ARTICLE 14</strong></span><strong>&nbsp;: ANNULATION ET INEFFICACIT&Eacute; DES CLAUSES <span>&nbsp;</span></strong></p>
        <p>La nullit&eacute;<span>&nbsp;&nbsp;</span>ou l&rsquo;impossibilit&eacute;<span>&nbsp;&nbsp;</span>de mise en &oelig;uvre de l&rsquo;une des quelconques clauses des pr&eacute;sentes CGU, si elle ne remet pas en cause notablement l&rsquo;&eacute;quilibre contractuel, n&rsquo;affectera que la clause concern&eacute;e et n&rsquo;entra&icirc;nera pas l&rsquo;annulation des pr&eacute;sentes CGU. <span>&nbsp;</span></p>
        <p>L&rsquo;Utilisateur s&rsquo;engage &agrave; lire attentivement le contenu du pr&eacute;sent document qui inclut les Conditions G&eacute;n&eacute;rales d&rsquo;Utilisation du Service, et accepte express&eacute;ment et sans r&eacute;serve toutes les r&egrave;gles et obligations qui y sont expos&eacute;es. <span>&nbsp;</span></p>
        <p ><span>&nbsp;</span></p>
        <p ><span>&nbsp;</span></p>
        <p><span>&nbsp;</span></p>
        </div>
      </div>
  );
}

export default Conditions;